### ISSUE TITLE
Docstring for fnft_nsev_cstype_t is incomplete

### ISSUE THREAD

**Issue by xmhk** [FastNFT/FNFT#16]
Hello,
the docstring for fnft_nsev_cstype_t in FNFT/include/fnft_nsev.h is incomplete:

it describes 
- fnft_nsev_cstype_REFLECTION_COEFFICIENT
- fnft_nsev_cstype_AB

but there is not description for the third option,
- fnft_nsev_cstype_BOTH

which should affect the size of contspec array that should be submitted

regards, Christoph

**Comment by wahls** [comment]
Dear Christoph,

Thanks for the report. I fixed this in the branch I am currently working on (c89c3cd296aeb2fa8baa0b00b6069f5f29ba9f9d). The fix should tickle down into the next minor release (0.2.0).

Just FYI, the size of the array should be 3M for the BOTH method. The first M values are those returned by the REFLECTION_COEFFICIENT method, the following 2M those returned by the AB method.

Best, Sander
