### ISSUE TITLE
fnft__akns_fscatter_test_2split6A fails in development

### ISSUE THREAD

**Issue by marbre** [FastNFT/FNFT#25]
Tested with gcc 6.4.0 and Gentoo Linux. The test fails on development (commit 79388e1).

```
14: Test command: /home/brehler/Development/FNFT/test/fnft__akns_fscatter/fnft__akns_fscatter_test_2split6A
14: Test timeout computed to be: 9.99988e+06
14: FNFT Error: Test failed.
14:  in akns_fscatter_test_2split6A(129)-0.1.1-dev
1/1 Test #14: fnft__akns_fscatter_test_2split6A ...***Failed    0.00 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.00 sec

The following tests FAILED:
         14 - fnft__akns_fscatter_test_2split6A (Failed)
```

**Comment by wahls** [comment]
Thanks for the report! Could you please recompile after passing the option `-DDEBUG=ON` to cmake, run the test manually, and post the output here? That should allow us to see what is going on.

**Comment by marbre** [comment]
The error is the following:
```
error without normalization = 6.4e-14 < 5.8e-14
FNFT Error: Test failed.
 in akns_fscatter_test_2split6A(129)-0.1.1-dev
```

**Comment by wahls** [comment]
Thanks. This looks as if the error bound is a bit too conservative on your system.
It has recently already been increased by @PJ-Prins in 6801eca4bb9acb89e76fca3ecaacadb7c104d3a1
Peter, could you please increase once more?

**Comment by PJ-Prins** [comment]
See https://github.com/FastNFT/FNFT/pull/26
