### ISSUE TITLE
FFTW problem

### ISSUE THREAD

**Issue by esf0** [FastNFT/FNFT#67]
I am writing to share a solution to one problem. If you have the following error during compilation:
```
usr/bin/ld: /usr/local/lib/libfftw3.a(assert.o): relocation R_X86_64_PC32 against symbol `stdout@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
```
when you compile with the `-DENABLE_FFTW=ON` flag, then you have to rebuild the FFTW library with the `--enable-shared` flag. And then rebuild FNFT library.

**Comment by wahls** [comment]
Thanks for reporting.
