### ISSUE TITLE
Problems with installing gcc from scoop

### ISSUE THREAD

**Issue by c5566b** [FastNFT/FNFT#68]
As reported in this issues: [https://github.com/ScoopInstaller/Main/issues/1752], some of the mirror links related to installing gcc in the scoop is no longer accessible, is there any other ways of installing gcc?

**Comment by c5566b** [comment]
Recommend to try the approach mentioned by this thread: https://github.com/ScoopInstaller/Main/issues/1752#issuecomment-778569708

> one simple solution:

>1. open the `<scoopdir>/buckets/main/gcc.json`
>2. replace `http://repo.msys2.org/` to `http://mirrors.huaweicloud.com/msys2/`

**Comment by wahls** [comment]
Thank you for reporting. I understand that this quick solves the problem for now?

**Comment by c5566b** [comment]
Yes, the problem will be solved. But it requires the user to manually go to the gcc.json in the root path of the scoop. I think it will be better to update the installation instruction with something like this: 

Run the command

`iex (new-object net.webclient).downloadstring('https://get.scoop.sh')`

in the PowerShell to install Scoop. Now that the Scoop should be installed. Before we install the rest of the components required, go to the home directory of the scoop (it probably is something like: "C:\Users\\[your user name]\scoop " ), find the gcc.json file following this path: "\buckets\main\bucket". 

Open gcc.json with Notepad and replace `http://repo.msys2.org/` with `http://mirrors.huaweicloud.com/msys2/`

Then, run the commands

```
scoop install git
scoop install cmake
scoop install gcc
```

**Comment by wahls** [comment]
Solved with #72
