### ISSUE TITLE
support for M1 chip architecture on macOS

### ISSUE THREAD

**Issue by Yarden92** [FastNFT/FNFT#69]
Hey,
I'm trying to run my FNFT python project on my macbook which has M1 chip.

I've managed to install brew cmake and gcc (the latest gcc v11 not 7 as said).
and also to build using:
CC=gcc FC=gfortran cmake ..

and 159/160 tests passed, number 14 failed:
 14/160 Test  #14: fnft__akns_fscatter_test_2split6A .................................***Failed    0.44 sec

when I execute my python code (edited the auxilary path to <FNFT dir>lib/libfnft.0.4.1.dylib (tried all 3  *dylib files) I get the following error:

OSError: dlopen(/<FNFT dir>/lib/libfnft.0.dylib, 6): no suitable image found.  Did find:
	/<FNFT dir>/lib/libfnft.0.dylib: mach-o, but wrong architecture
	/<FNFT dir>/lib/libfnft.0.4.1.dylib: mach-o, but wrong architecture

Any chance to get a workaround or M1 support?

**Comment by wahls** [comment]
If that's the only test is failing, then FNFT is probably working well. The errors in the test differ slightly between platforms and compilers. Sometimes the error bounds in the tests turn out to be a little bit too tight on other architectures.

Since the tests compile, it seems that FNFT itself compiles fine. This seems more related to the Python interface?

**Comment by xmhk** [comment]
Hi yarden and sander,

looks like a python error for me too. googling "mac m1 OSError: dlopen" gives me several sites reporting errors when the import of some library failed. What seems to solve the issue in some cases is to use the homebrew python version, as in e.g. https://github.com/pyusb/pyusb/issues/355

Yarden, do you know which version of python you are using? IDK, is there some python shipped with the Mac OS itself?

Best, Christoph

**Comment by Yarden92** [comment]
> Yarden, do you know which version of python you are using? IDK, is there some python shipped with the Mac OS itself?

Hi! thanks for the reply, sorry for the delay,
I'm running python 3.8 (tried also 3.9, same)

I'm not sure about the built-in python by the mac os, I've downloaded one on my own..
There is though a python 2.7 installed (not by me, perhaps it came with the OS).

**Comment by xmhk** [comment]
Hello,
Unfortunately, I'm little bit in the dark here and I think I have no good chance to reproduce this issue. 
As far as googling brought me, I see that this error seems to be related to the way stuff is compiled on the new  M1 processor. 
Something similar happened here: https://github.com/apple/tensorflow_macos/issues/65

Currently, Mac OS on M1 supports ARM (M1), but you can also run legacy X86_64.  As M1 is new, I suppose building everything for this architecture is not completely implemented in all build-tools, Makefiles, etc. Furthermore, depending on the compiler settings, you can compile code for both architectures, and run the old x86_64 stuff in some compatibility layer (I think called Rosetta). The problem arises, when you **mix** architectures, e.g. when you are using the compatibility mode for the python interpreter and try to load a dynamic library which is compiled for M1. Or vice versa.
At least in my understanding, this is what the error  
`//lib/libfnft.0.dylib: mach-o, but wrong architecture`  tries to tell us.

Do you use the command line when you try to start e.g. the example python script? Or do you use some IDE?
If you use a command line (Terminal) could you check the output of the following commands?

1. open the terminal and enter `uname -a`   (this tells you the architecture, indicated by the  **arm64** or **x86_64** flag)
2. go to the folder which contains the dynamic library and enter `file libfnft.0.4.1.dylib`   (this tells which architecture FNFT is build for)
3. check your python interpreter. I'm not sure this should be one of these commands
    - `file $(which python)`
    - `file $(which python3)`
    - `file $(which python3.9)`

For me (linux), all three outputs from 1.-3. contain the exact same architecture flag (in my case  **x86_64**).

To solve your issue, I guess you must find a way to get some environment in which the python interpreter and the library have exactly the same architecture. This may work e.g. using homebrew and pyenv, but honestly I am not sure how to achieve this in practice, as I have no Mac M1 to test this. 

Best, Christoph

**Comment by Yarden92** [comment]
Okay, so after finally going through all of this I can confirm that indeed, the python interpreter architecture was wrong.

The PC (1) as well as the FNFT's output (2) resulted architecture of arm64
while the python3/python3.9 resulted architecture of x86

I've double checked and indeed if you simply download the basic python for mac from python.org, it is for x86.

But if you go to https://www.python.org/downloads/macos/ and Download [macOS 64-bit universal2 installer](https://www.python.org/downloads/macos/#:~:text=bit%20Intel%20installer-,Download%20macOS%2064-bit%20universal2%20installer,-Python%203.8.11%20-%20June)

You'll get the correct architecture (actually it includes both).

You can verify it during the installation:
![image](https://user-images.githubusercontent.com/19271465/129356642-142481ae-1151-429e-b39a-08d6c636ecf6.png)


so just to summarize and emphasize for future readers:
### **IT NOW WORKS!**
