### ISSUE TITLE
Windows 11 Install

### ISSUE THREAD

**Issue by Armaroli** [FastNFT/FNFT#80]
Hello,

I installed FNFT on Windows 11.

I get these errors while testing
        233 - fnft_nsev_inverse_test_truncated_soliton_2split2_modal (Exit code 0xc0000139
)
        234 - fnft_version_test (Exit code 0xc0000139
)
Errors while running CTest
Output from these tests are in: C:/Users/andre/FNFT/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
mingw32-make: *** [Makefile:70: test] Error 8

Moreover, I find two Matlab folders one with capital m one with small m. I copied all files libmex... mex... in both folders and the examples fail

Invalid MEX-file '~\FNFT\build\mex_fnft_kdvv.mexw64': Impossibile trovare la procedura specificata.

I remember I managed to install FNFT on a different PC in 2022 with Windows 10 and worked perfectly.

Thank you for your help.

Best regards,

Andrea

**Comment by Armaroli** [comment]
I rectify. I tried on a Win10 PC and it doesn't work either. 

Thank you

**Comment by wahls** [comment]
Dear Andrea,

Many thanks for the report. Just to clarify, you are using release 0.5? Maybe you were installing a previous release in the past?

For me (on Linux) everything works fine, so I'll need some help from your side.

Regarding the first failing test, could you please do the following for me?

Remove everything in the build folder and rebuild after rerunning cmake with the "-DDEBUG=ON" flag. Then run the failing test executable directly in the shell (i.e., not via ctest). The test should now print some errors. Could you please report these back here?

Regarding the other test, it's not clear to me what went wrong there. If you run it directly as well, does it return some output?

Regarding the Matlab folder issue, I'm also not sure what's going on. I'll see if I can get my hands on a Windows PC next week.

Best, Sander

**Comment by Armaroli** [comment]
Dear Sander,

Thank you for the quick response. 

1. I tried different versions. What I was referring to yesterday was 0.5. 
2. I realized that scoop was broken. I reinstalled it. Now tests are passed both for 0.5 and for older versions. 
Apart from

The following tests FAILED:
        151 - fnft_nsep_test_numerical_focusing_1_newton (SEGFAULT)
        152 - fnft_nsep_test_numerical_focusing_2 (SEGFAULT)
Errors while running CTest
3. I updated Visual C++ to the last version
4. I removed mingw from Matlab Add-ons

Unfortunately, I still get Invalid MEX-file '~\FNFT\matlab\mex_fnft_kdvv.mexw64': The specified module cannot be found

Best regards,

Andrea

**Comment by wahls** [comment]
Dear Andrea,

I see. For my understanding, which compiler is cmake now using - MinGW or Visual C++? So far I only heard about MinGW.

Regarding the segfaulting tests, could you still run them in debug mode as explained earlier (empty build, run cmake with -DDEBUG=ON flag, run test executables directly in terminal, report any messages)?

If mingw comes with the GNU debugger, you could also run the segfaulting tests in there to see where the problem occurs. For executables compiled in DEBUG mode, it shows the code where it is failing. At least under Linux, you simply execute something like `gdb test/fnft_nsep/fnft_nsep_test_numerical_focusing_1_newton` in the shell and then enter the command `run`.

MEX support on Windows can be difficult. Did you also copy the libfnft... files into the matlab folder (it's not mentioned in your first post)? In the past, when we had problems with Matlab on Windows, it was often that there was a mismatch between the used compiler and Matlab in terms of 32bit vs 64bit architectures (mingw provides both variants).

Please let me know any findings. As mentioned, I'll can also try to get my hands on a Win11 machine next week necessary.

Best, Sander

**Comment by Armaroli** [comment]
Dear Sander,

thank you for your answer. Indeed, I carefully followed the instructions, as I did in 2022 (at that time, there was an open issue about mingw vs gcc). So, I use MinGW, copy files from build to FNFT/matlab (with small m). 

I'm using Matlab 2023a on both PCs I tried last week. Could it be the source of this issue? I will try to go deep into Dependency Walker and better understand what's on. I will be grateful if you can try yourself and let me know. 

Best regards,

Andrea

**Comment by wahls** [comment]
Dear Andrea,

Regarding the segfaults: 

Could you please empty your build folder and then use
```
cmake .. -G"MinGW Makefiles" -DMACHINE_SPECIFIC_OPTIMIZATION=OFF
mingw32-make -j4
mingw32-make -j4 test
```
to build and run the tests? 

At the Win11 machine I have here, this resolves the segfaults.

If I have time, I'll look into the Matlab issue tomorrow.

Best, Sander

**Comment by wahls** [comment]
Dear Andrea,

I now had a chance to test the Matlab interface on Win11. Here it works just fine, but I only have access to Matlab 2022b.

Maybe it's an issue that's new for Matlab 2023a... Do you have the possibility to test another Matlab version?

Best, Sander

**Comment by Armaroli** [comment]
Dear Sander,

thank you very much for your feedback. I am trying a different version. 

As for the dlls: should I copy also *.dll.a files into matlab directory?

Which matlab directory, the one ./FNFT/build or the one in /FNFT?

I find it quite strange, because I clearly remember of having used the FNFT library before without any issue.

Happy Easter!

Best,

Andrea

**Comment by wahls** [comment]
Dear Andrea,

You are welcome. Please let me know if another version fixes the issue. 

I only had to copy the .mex64 files and libfnft.dll. They belong into the ./FNFT/matlab folder, which is the one you should add to the Matlab path.

Happy Easter to you, too!

Best, Sander

**Comment by wahls** [comment]
Dear Andrea,

I was just wondering if there were any news? If not, then I would close this issue.

Best, Sander

**Comment by Armaroli** [comment]
Dear Sander,

I tried different Matlab versions, but this was not the culprit.

Trying on a third PC of mine, it works! I still do not understand what causes this issue: apparently missing dlls. 

Thank you for your assistance!

Best,

Andrea
